FikirDeposu/Controllers/IdeaController.cs
using FikirDeposu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FikirDeposu.Controllers
{
    public class IdeaController : Controller
    {
        Context db = new Context();
        public ActionResult IdeaAdd()
        {
            return View();
        }

        public string AddIdea(Ideas idea)
        {
            UserDetails user;
            if (Session["firstLoggedInUser"] != null)
            {
                user =(UserDetails) Session["firstLoggedInUser"];
            }else
            {
                user = (UserDetails)Session["loggedInUser"];
            }
            UserDetails dbUser = db.UserDetails.Where(x => x.email == user.email).SingleOrDefault();
            idea.ideaDate = DateTime.Now;
            idea.number = new Random().Next(0, 100);
            idea.isActive = true;
            idea._event = "Yeni Giriş";
            dbUser.Ideas.Add(idea);
            db.Ideas.Add(idea);
            db.SaveChanges();

            return "success";
        }

        public string UpdateIdea(int ideaID,string name,string description,string status,string _event)
        {
            Ideas idea = db.Ideas.Where(x => x.ideaID == ideaID && x.isActive==true).SingleOrDefault();
            idea.name = name;
            idea.description = description;
            idea.status = status;
            idea._event = _event;
            if (_event == "Kapatıldı")
                idea.isActive = false;
            db.SaveChanges();
            return "success";
        }
        public string CloseIdea(int ideaID)
        {
            Ideas idea = db.Ideas.Where(x => x.ideaID == ideaID).SingleOrDefault();
            idea.isActive = false;
            idea.clasureDate = DateTime.Now;
            idea._event = "Kapatıldı";
            db.SaveChanges();

            return "success";
        }

    }
}

FikirDeposu/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link href="/Content/web/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="/Content/web/css/style.css" rel='stylesheet' type='text/css' />
    <link rel="icon" href="/Content/web/favicon.ico" type="image/x-icon">
    <link href="/Content/web/css/font-awesome.css" rel="stylesheet">
    <script src="/Content/web/js/jquery-1.11.1.min.js"></script>
    <script src="/Content/web/js/modernizr.custom.js"></script>
    <link href='~/Content/web/google1.css' rel='stylesheet' type='text/css'>
    <link href='~/Content/web/google2.css' rel='stylesheet' type='text/css'>
    <script src="/Content/web/js/metisMenu.min.js"></script>
    <script src="/Content/web/js/custom.js"></script>
    <link href="/Content/web/css/custom.css" rel="stylesheet">
   
</head>
<body class="cbp-spmenu-push">
    <div class="main-content">
        <div class="sidebar" role="navigation">
            <div class="navbar-collapse">
                <nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right dev-page-sidebar mCustomScrollbar _mCS_1 mCS-autoHide mCS_no_scrollbar" id="cbp-spmenu-s1">
                    <div class="scrollbar scrollbar1">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="@Url.Action("Home","User")"><i class="fa fa-home nav_icon"></i>Anasayfa</a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-lightbulb-o nav_icon"></i>Fikirler <span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level collapse">
                                    <li>
                                        <a href="@Url.Action("IdeaAdd", "Idea")">Fikir Ekle</a>
                                    </li>
                                    <li>
                                        <a href="grid.html">Fikirlerim</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="@Url.Action("Login","User")"><i class="fa fa-sign-out nav_icon"></i>çıkış</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <div class="sticky-header header-section ">
            <div class="header-left">
                <div class="logo">
                    <a href="@Url.Action("Home","User")"><h1>Fikir Deposu</h1></a>
                </div>
                @*<div class="user-right">
                    <div class="profile_details_left">
                        <div class="profile_details">
                            <ul>
                                <li class="dropdown profile_details_drop">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <div class="profile_img">
                                            <span class="prfil-img"><img src="/Content/web/images/a.png" alt=""> </span>
                                            <div class="clearfix"></div>
                                        </div>
                                    </a>
                                    <ul class="dropdown-menu drp-mnu">
                                        <li> <a href="#"><i class="fa fa-cog"></i> Settings</a> </li>
                                        <li> <a href="#"><i class="fa fa-user"></i> Profile</a> </li>
                                        <li> <a href="#"><i class="fa fa-sign-out"></i> Logout</a> </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>*@
                <div class="clearfix"> </div>
            </div>
            @*<div class="profile_medile">
                <ul class="nofitications-dropdown">
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i><span class="badge">3</span></a>
                        <ul class="dropdown-menu anti-dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new messages</h3>
                                </div>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="user_img"><img src="/Content/web/images/1.png" alt=""></div>
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor amet</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a>
                            </li>
                            <li class="odd">
                                <a href="#">
                                    <div class="user_img"><img src="/Content/web/images/2.png" alt=""></div>
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor amet </p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="user_img"><img src="/Content/web/images/3.png" alt=""></div>
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor amet </p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a>
                            </li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all messages</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown head-dpdn">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-bell"></i><span class="badge blue">3</span></a>
                        <ul class="dropdown-menu anti-dropdown-menu">
                            <li>
                                <div class="notification_header">
                                    <h3>You have 3 new notification</h3>
                                </div>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="user_img"><img src="/Content/web/images/2.png" alt=""></div>
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor amet</p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a>
                            </li>
                            <li class="odd">
                                <a href="#">
                                    <div class="user_img"><img src="/Content/web/images/1.png" alt=""></div>
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor amet </p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <div class="user_img"><img src="/Content/web/images/3.png" alt=""></div>
                                    <div class="notification_desc">
                                        <p>Lorem ipsum dolor amet </p>
                                        <p><span>1 hour ago</span></p>
                                    </div>
                                    <div class="clearfix"></div>
                                </a>
                            </li>
                            <li>
                                <div class="notification_bottom">
                                    <a href="#">See all notifications</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>*@
            <div class="header-right">
                <div class="search-box">
                    <form class="input">
                        <input class="sb-search-input input__field--madoka" placeholder="Arama..." type="search" id="input-31">
                    </form>
                </div>
                <button id="showLeftPush"><i class="fa fa-bars"></i></button>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
        <div id="page-wrapper">
            <div class="main-page">
                <div class="blank-page">
                   @RenderBody()
                </div>
            </div>
        </div>

        @*<div class="copy-section">
            <p>&copy; 2019 Fikir Deposu. All rights reserved | Design by <a href="http://abdullahfurkankoc.com">Furkan KOÇ</a></p>
        </div>*@
    </div>
    <script src="/Content/web/js/classie.js"></script>
    <script>
					var menuLeft = document.getElementById( 'cbp-spmenu-s1' ),
						showLeftPush = document.getElementById( 'showLeftPush' ),
						body = document.body;

					showLeftPush.onclick = function() {
						classie.toggle( this, 'active' );
						classie.toggle( body, 'cbp-spmenu-push-toright' );
						classie.toggle( menuLeft, 'cbp-spmenu-open' );
						disableOther( 'showLeftPush' );
					};


					function disableOther( button ) {
						if( button !== 'showLeftPush' ) {
							classie.toggle( showLeftPush, 'disabled' );
						}
					}
    </script>
    <script type="text/javascript" src="/Content/web/js/bootstrap.min.js"></script>
    <script src="/Content/web/js/jquery.nicescroll.js"></script>
    <script src="/Content/web/js/scripts.js"></script>
</body>
</html>